### ISSUE TITLE
complex holidays

### ISSUE THREAD

**Issue by jamesfoster** [noctivityinc/tickle#4]
Hi

When I saw you implemented holidays I thought about UK Bank holidays.

Most bank holidays are fixed dates or simple expressions, however christmas, boxing day and easter are more complex.

christmas bank holiday is the 25th of december unless that's a weekend, in which case it's the monday after (so it could be the 26th or 27th)

boxing day is the day after the christmas bank holiday unless that's a weekend, in which case it's the monday after.

so something like:

```
"the first weekday starting Dec 25th"
```

and

```
"the first weekday after the first weekday starting Dec 25th"
```

possible??

Easter is based on the phases of the moon so I doubt that's very doable.

**Comment by noctivityinc** [comment]
Phases of the moon would be interesting.  Not sure where you would get that.

As for the rest, definitely possible but outside my current focus.  If you fork and add let me know and Ill merge.
