### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by jamesfoster** [noctivityinc/tickle#5]
Is tickle extendable into other languages? given that, not only do the words change, but also the order of words change in the different grammars.

If not could you give some thought to structuring tickle so that it's easier to extend with language "packs" of some sort?

Thanks

**Comment by noctivityinc** [comment]
It's definitely extendable now.  Tickle works by breaking down phrases into word "tokens" and then converting the tokens into parable dates.  You can easily add additional rules for words in other languages. The order of the words should not really mater.
